"""add table defect_messages

Revision ID: 17d3b98f292f
Revises: 6220dbf972a1
Create Date: 2025-09-30 14:05:19.723643

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '17d3b98f292f'
down_revision = '6220dbf972a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('defect_messages',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='消息ID'),
    sa.Column('send_to_user_id', sa.BigInteger(), nullable=False, comment='接收用户ID'),
    sa.Column('send_from_user_id', sa.BigInteger(), nullable=True, comment='发送用户ID'),
    sa.Column('send_time', sa.DateTime(), nullable=False, comment='发送时间'),
    sa.Column('defect_id', sa.BigInteger(), nullable=False, comment='缺陷单ID'),
    sa.Column('message_type', sa.String(length=50), nullable=False, comment='消息类型'),
    sa.Column('content', sa.Text(), nullable=False, comment='消息内容模板'),
    sa.Column('extra_params', sa.JSON(), nullable=True, comment='额外参数（驳回原因、跟催原因等）'),
    sa.Column('is_closed', sa.Boolean(), nullable=True, comment='是否已关闭'),
    sa.Column('created_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine='InnoDB'
    )

    with op.batch_alter_table('doc_files', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=mysql.TINYINT(display_width=11),
               type_=sa.Integer(),
               comment=None,
               existing_comment='根分级\r\n0：缺陷\r\n1：需求\r\n2：立项',
               existing_nullable=True)
        batch_op.alter_column('markdown',
               existing_type=mysql.LONGTEXT(collation='utf8mb4_bin'),
               comment=None,
               existing_comment='评估规则文档html(缺陷、需求、立项)',
               existing_nullable=True)
        batch_op.alter_column('html',
               existing_type=mysql.LONGTEXT(collation='utf8mb4_bin'),
               comment=None,
               existing_comment='评估规则文档markdown(缺陷、需求、立项)',
               existing_nullable=True)
        batch_op.alter_column('html_content',
               existing_type=mysql.LONGTEXT(collation='utf8mb4_bin'),
               comment=None,
               existing_comment='立项xx内容总结规则',
               existing_nullable=True)
        batch_op.alter_column('markdown_content',
               existing_type=mysql.LONGTEXT(collation='utf8mb4_bin'),
               comment=None,
               existing_comment='立项xx内容总结规则',
               existing_nullable=True)
        batch_op.alter_column('cammand',
               existing_type=mysql.TEXT(collation='utf8mb4_bin'),
               comment=None,
               existing_comment='命令',
               existing_nullable=True)
        batch_op.alter_column('title_show',
               existing_type=mysql.VARCHAR(collation='utf8mb4_bin', length=255),
               comment=None,
               existing_comment='显示标题',
               existing_nullable=True,
               existing_server_default=sa.text("''"))
        batch_op.alter_column('big_title_show',
               existing_type=mysql.VARCHAR(collation='utf8mb4_bin', length=255),
               comment=None,
               existing_comment='显示大标题',
               existing_nullable=True)
        batch_op.alter_column('child_type_1',
               existing_type=mysql.TINYINT(display_width=4),
               type_=sa.Integer(),
               comment=None,
               existing_comment='第一子分级',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('child_type_2',
               existing_type=mysql.TINYINT(display_width=4),
               type_=sa.Integer(),
               comment=None,
               existing_comment='第二子分级',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('step',
               existing_type=mysql.TINYINT(display_width=4),
               type_=sa.Integer(),
               comment=None,
               existing_comment='标记哪一个step，和ai_sug_score.step对应',
               existing_nullable=True,
               existing_server_default=sa.text("'-1'"))


    with op.batch_alter_table('email_user_right', schema=None) as batch_op:
        batch_op.alter_column('type_0',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='缺陷',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('type_1',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='需求',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('type_2',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='立项',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))


    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='手机用户，0：刚填写手机密码；1：注册完填写完公司\r\n\r\n邮件用户，0未邮箱激活，1已激活',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.INTEGER(display_width=11),
               comment='手机用户，0：刚填写手机密码；1：注册完填写完公司\r\n\r\n邮件用户，0未邮箱激活，1已激活',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))


    with op.batch_alter_table('email_user_right', schema=None) as batch_op:
        batch_op.alter_column('type_2',
               existing_type=mysql.INTEGER(display_width=11),
               comment='立项',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('type_1',
               existing_type=mysql.INTEGER(display_width=11),
               comment='需求',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('type_0',
               existing_type=mysql.INTEGER(display_width=11),
               comment='缺陷',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('doc_files', schema=None) as batch_op:
        batch_op.alter_column('step',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=4),
               comment='标记哪一个step，和ai_sug_score.step对应',
               existing_nullable=True,
               existing_server_default=sa.text("'-1'"))
        batch_op.alter_column('child_type_2',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=4),
               comment='第二子分级',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('child_type_1',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=4),
               comment='第一子分级',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('big_title_show',
               existing_type=mysql.VARCHAR(collation='utf8mb4_bin', length=255),
               comment='显示大标题',
               existing_nullable=True)
        batch_op.alter_column('title_show',
               existing_type=mysql.VARCHAR(collation='utf8mb4_bin', length=255),
               comment='显示标题',
               existing_nullable=True,
               existing_server_default=sa.text("''"))
        batch_op.alter_column('cammand',
               existing_type=mysql.TEXT(collation='utf8mb4_bin'),
               comment='命令',
               existing_nullable=True)
        batch_op.alter_column('markdown_content',
               existing_type=mysql.LONGTEXT(collation='utf8mb4_bin'),
               comment='立项xx内容总结规则',
               existing_nullable=True)
        batch_op.alter_column('html_content',
               existing_type=mysql.LONGTEXT(collation='utf8mb4_bin'),
               comment='立项xx内容总结规则',
               existing_nullable=True)
        batch_op.alter_column('html',
               existing_type=mysql.LONGTEXT(collation='utf8mb4_bin'),
               comment='评估规则文档markdown(缺陷、需求、立项)',
               existing_nullable=True)
        batch_op.alter_column('markdown',
               existing_type=mysql.LONGTEXT(collation='utf8mb4_bin'),
               comment='评估规则文档html(缺陷、需求、立项)',
               existing_nullable=True)
        batch_op.alter_column('type',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=11),
               comment='根分级\r\n0：缺陷\r\n1：需求\r\n2：立项',
               existing_nullable=True)

        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('ai_sug_score.id'), 'ai_sug_score', ['val_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.alter_column('val_id',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(collation='utf8mb4_bin', length=128),
               comment=None,
               existing_comment='',
               existing_nullable=True)

    op.drop_table('defect_messages')
    # ### end Alembic commands ###
