"""add_defect_tables_0830

Revision ID: 1ad37ce49f1d
Revises: f7fa181e0663
Create Date: 2025-08-30 12:55:13.903283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ad37ce49f1d'
down_revision = 'f7fa181e0663'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('defect_stages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='阶段记录ID，主键'),
    sa.Column('assigned_to', sa.Integer(), nullable=True, comment='阶段负责人ID'),
    sa.Column('completed_by', sa.Integer(), nullable=True, comment='阶段完成人ID'),
    sa.Column('notes', sa.Text(), nullable=True, comment='阶段备注信息（记录 原因分析的弃用，将被弃用的内容记录到这里）'),
    sa.Column('created_time', sa.DateTime(), nullable=True, comment='阶段创建时间'),
    sa.Column('updated_time', sa.DateTime(), nullable=True, comment='阶段最后更新时间'),
    sa.Column('completed_time', sa.DateTime(), nullable=True, comment='阶段完成时间'),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'COMPLETED', 'REJECTED', 'CANCELLED', name='stagestatus'), nullable=True, comment='阶段状态'),
    sa.Column('rejection_count', sa.Integer(), nullable=True, comment='阶段被驳回次数'),
    sa.ForeignKeyConstraint(['assigned_to'], ['user.user_id'], ),
    sa.ForeignKeyConstraint(['completed_by'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('defect_stages', schema=None) as batch_op:
        batch_op.create_index('ix_defect_stages_assigned_to', ['assigned_to'], unique=False)
        batch_op.create_index('ix_defect_stages_status', ['status'], unique=False)

    op.create_table('defect_analysis_divisions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='分工记录ID，主键'),
    sa.Column('defect_stage_id', sa.Integer(), nullable=False, comment='关联的缺陷阶段ID'),
    sa.Column('module', sa.String(length=255), nullable=False, comment='负责模块'),
    sa.Column('version', sa.String(length=100), nullable=False, comment='版本信息'),
    sa.Column('due_date', sa.Date(), nullable=False, comment='截止日期'),
    sa.Column('assignee_id', sa.Integer(), nullable=False, comment='负责人ID'),
    sa.Column('action_plan', sa.Text(), nullable=False, comment='行动计划'),
    sa.Column('created_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(), nullable=True, comment='最后更新时间'),
    sa.Column('reminder_count', sa.Integer(), nullable=True, comment='跟催次数'),
    sa.Column('last_reminder_time', sa.DateTime(), nullable=True, comment='最后跟催时间'),
    sa.ForeignKeyConstraint(['assignee_id'], ['user.user_id'], ),
    sa.ForeignKeyConstraint(['defect_stage_id'], ['defect_stages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('defect_analysis_divisions', schema=None) as batch_op:
        batch_op.create_index('ix_divisions_assignee_id', ['assignee_id'], unique=False)
        batch_op.create_index('ix_divisions_defect_stage_id', ['defect_stage_id'], unique=False)

    op.create_table('defect_locale_invitations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='邀请ID，主键'),
    sa.Column('defect_stage_id', sa.Integer(), nullable=False, comment='关联的缺陷阶段ID'),
    sa.Column('inviter_id', sa.Integer(), nullable=False, comment='邀请人ID'),
    sa.Column('invitee_id', sa.Integer(), nullable=True, comment='被邀请人ID'),
    sa.Column('invitation_reason', sa.Text(), nullable=False, comment='邀请原因'),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', 'CANCELLED', name='invitationstatus'), nullable=True, comment='邀请状态'),
    sa.Column('reminder_count', sa.Integer(), nullable=True, comment='跟催次数'),
    sa.Column('last_reminder_time', sa.DateTime(), nullable=True, comment='最后跟催时间'),
    sa.Column('rejection_reason', sa.Text(), nullable=True, comment='驳回原因'),
    sa.Column('rejection_time', sa.DateTime(), nullable=True, comment='驳回时间'),
    sa.Column('created_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(), nullable=True, comment='最后更新时间'),
    sa.ForeignKeyConstraint(['defect_stage_id'], ['defect_stages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invitee_id'], ['user.user_id'], ),
    sa.ForeignKeyConstraint(['inviter_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('defect_locale_invitations', schema=None) as batch_op:
        batch_op.create_index('ix_invitations_defect_stage_id', ['defect_stage_id'], unique=False)
        batch_op.create_index('ix_invitations_invitee_id', ['invitee_id'], unique=False)
        batch_op.create_index('ix_invitations_status', ['status'], unique=False)

    op.create_table('defect_stage_collaborators',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='协作记录ID，主键'),
    sa.Column('defect_stage_id', sa.Integer(), nullable=False, comment='关联的缺陷阶段ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='协作者用户ID'),
    sa.Column('role', sa.Enum('PRIMARY', 'COLLABORATOR', name='collaboratorrole'), nullable=True, comment='协作者角色'),
    sa.Column('joined_time', sa.DateTime(), nullable=True, comment='加入时间'),
    sa.Column('left_time', sa.DateTime(), nullable=True, comment='离开时间'),
    sa.Column('invitation_id', sa.Integer(), nullable=True, comment='关联的邀请ID'),
    sa.ForeignKeyConstraint(['defect_stage_id'], ['defect_stages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invitation_id'], ['defect_locale_invitations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('defect_stage_id', 'user_id', name='unique_collaborator'),
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('defect_stage_collaborators', schema=None) as batch_op:
        batch_op.create_index('ix_collaborators_defect_stage_id', ['defect_stage_id'], unique=False)
        batch_op.create_index('ix_collaborators_user_id', ['user_id'], unique=False)

    op.create_table('defect_stage_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='阶段数据ID，主键'),
    sa.Column('defect_stage_id', sa.Integer(), nullable=False, comment='关联的缺陷阶段ID'),
    sa.Column('data_type', sa.Enum('DEFECT_DESCRIPTION', 'CAUSE_ANALYSIS', 'SOLUTION', 'TEST_RESULT', name='datatype'), nullable=False, comment='数据类型，对应问题描述、原因分析、解决措施及验证4个特殊阶段'),
    sa.Column('invitation_id', sa.Integer(), nullable=True, comment='关联的邀请ID'),
    sa.Column('division_id', sa.Integer(), nullable=True, comment='关联的分工ID'),
    sa.Column('content', sa.JSON(), nullable=False, comment='数据内容'),
    sa.Column('is_draft', sa.Boolean(), nullable=True, comment='是否草稿——仅本人可见'),
    sa.Column('submitted_by', sa.Integer(), nullable=False, comment='提交人ID'),
    sa.Column('is_combined', sa.Boolean(), nullable=True, comment='是否为合并后的数据'),
    sa.Column('is_current', sa.Boolean(), nullable=True, comment='是否为当前最新数据'),
    sa.Column('evaluation_method', sa.Enum('AUTO', 'MANUAL', name='evaluationmethod'), nullable=True, comment='评分方式'),
    sa.Column('ai_suggestion', sa.Text(), nullable=True, comment='AI评估建议'),
    sa.Column('ai_score', sa.Integer(), nullable=True, comment='AI评估分数'),
    sa.Column('ai_evaluation_time', sa.DateTime(), nullable=True, comment='AI评估时间'),
    sa.Column('created_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(), nullable=True, comment='最后更新时间'),
    sa.ForeignKeyConstraint(['defect_stage_id'], ['defect_stages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['division_id'], ['defect_analysis_divisions.id'], ),
    sa.ForeignKeyConstraint(['invitation_id'], ['defect_locale_invitations.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('defect_stage_id', 'data_type', 'is_current', name='uk_stage_data_type'),
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('defect_stage_data', schema=None) as batch_op:
        batch_op.create_index('ix_stage_data_data_type', ['data_type'], unique=False)
        batch_op.create_index('ix_stage_data_defect_stage_id', ['defect_stage_id'], unique=False)
        batch_op.create_index('ix_stage_data_submitted_by', ['submitted_by'], unique=False)

    op.create_table('defects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='缺陷ID，主键'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='缺陷标题'),
    sa.Column('description', sa.Text(), nullable=True, comment='缺陷详细描述'),
    sa.Column('severity', sa.String(length=50), nullable=False, comment='缺陷严重程度'),
    sa.Column('creator_id', sa.Integer(), nullable=False, comment='缺陷创建者ID'),
    sa.Column('version_id', sa.Integer(), nullable=True, comment='关联版本ID'),
    sa.Column('project_id', sa.Integer(), nullable=True, comment='关联项目ID'),
    sa.Column('is_duplicate', sa.Boolean(), nullable=True, comment='是否为重复缺陷'),
    sa.Column('duplicate_source_id', sa.Integer(), nullable=True, comment='重复的源缺陷ID'),
    sa.Column('current_stage_id', sa.Integer(), nullable=True, comment='当前所处阶段ID'),
    sa.Column('status', sa.Enum('DRAFT', 'OPEN', 'RESOLVED', 'CLOSED', 'REJECTED', name='defectstatus'), nullable=True, comment='缺陷整体状态'),
    sa.Column('created_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(), nullable=True, comment='最后更新时间'),
    sa.ForeignKeyConstraint(['creator_id'], ['user.user_id'], ),
    sa.ForeignKeyConstraint(['current_stage_id'], ['defect_stages.id'], ),
    sa.ForeignKeyConstraint(['duplicate_source_id'], ['defects.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('defects', schema=None) as batch_op:
        batch_op.create_index('ix_defects_creator_id', ['creator_id'], unique=False)
        batch_op.create_index('ix_defects_current_stage_id', ['current_stage_id'], unique=False)
        batch_op.create_index('ix_defects_project_id', ['project_id'], unique=False)
        batch_op.create_index('ix_defects_status', ['status'], unique=False)
        batch_op.create_index('ix_defects_version_id', ['version_id'], unique=False)

    op.create_table('defect_rejections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='驳回记录ID，主键'),
    sa.Column('defect_id', sa.Integer(), nullable=False, comment='关联的缺陷ID'),
    sa.Column('defect_stage_id', sa.Integer(), nullable=False, comment='关联的缺陷阶段ID'),
    sa.Column('rejection_type', sa.Enum('STAGE', 'INVITATION', 'ANALYSIS', 'SOLUTION', name='rejectiontype'), nullable=False, comment='驳回类型'),
    sa.Column('invitation_id', sa.Integer(), nullable=True, comment='关联的邀请ID'),
    sa.Column('stage_data_id', sa.Integer(), nullable=True, comment='阶段数据ID'),
    sa.Column('rejected_by', sa.Integer(), nullable=False, comment='驳回人ID'),
    sa.Column('reason', sa.Text(), nullable=False, comment='驳回原因'),
    sa.Column('previous_stage_id', sa.Integer(), nullable=True, comment='驳回后返回的阶段ID'),
    sa.Column('created_time', sa.DateTime(), nullable=True, comment='驳回时间'),
    sa.ForeignKeyConstraint(['defect_id'], ['defects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['defect_stage_id'], ['defect_stages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invitation_id'], ['defect_locale_invitations.id'], ),
    sa.ForeignKeyConstraint(['previous_stage_id'], ['defect_stages.id'], ),
    sa.ForeignKeyConstraint(['rejected_by'], ['user.user_id'], ),
    sa.ForeignKeyConstraint(['stage_data_id'], ['defect_stage_data.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('defect_rejections', schema=None) as batch_op:
        batch_op.create_index('ix_rejections_defect_id', ['defect_id'], unique=False)
        batch_op.create_index('ix_rejections_defect_stage_id', ['defect_stage_id'], unique=False)
        batch_op.create_index('ix_rejections_rejected_by', ['rejected_by'], unique=False)

    op.create_table('defect_reminders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='跟催记录ID，主键'),
    sa.Column('defect_id', sa.Integer(), nullable=False, comment='关联的缺陷ID'),
    sa.Column('defect_stage_id', sa.Integer(), nullable=False, comment='关联的缺陷阶段ID'),
    sa.Column('reminder_type', sa.Enum('ANALYSIS', 'SOLUTION', name='remindertype'), nullable=False, comment='跟催类型'),
    sa.Column('target_id', sa.Integer(), nullable=False, comment='跟催目标ID'),
    sa.Column('reminder_by', sa.Integer(), nullable=False, comment='跟催人ID'),
    sa.Column('reminder_time', sa.DateTime(), nullable=True, comment='跟催时间'),
    sa.Column('reminder_message', sa.Text(), nullable=True, comment='跟催内容'),
    sa.Column('reminder_status', sa.Enum('SENT', 'VIEWED', 'ACTED', name='reminderstatus'), nullable=True, comment='跟催状态'),
    sa.Column('action_time', sa.DateTime(), nullable=True, comment='处理时间'),
    sa.Column('action_notes', sa.Text(), nullable=True, comment='处理备注'),
    sa.Column('created_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(), nullable=True, comment='最后更新时间'),
    sa.ForeignKeyConstraint(['defect_id'], ['defects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['defect_stage_id'], ['defect_stages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reminder_by'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('defect_reminders', schema=None) as batch_op:
        batch_op.create_index('ix_reminders_defect_id', ['defect_id'], unique=False)
        batch_op.create_index('ix_reminders_defect_stage_id', ['defect_stage_id'], unique=False)
        batch_op.create_index('ix_reminders_reminder_by', ['reminder_by'], unique=False)
        batch_op.create_index('ix_reminders_reminder_type', ['reminder_type'], unique=False)

    op.create_table('defect_stage_combine_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='合并记录ID，主键'),
    sa.Column('defect_id', sa.Integer(), nullable=False, comment='关联的缺陷ID'),
    sa.Column('defect_stage_id', sa.Integer(), nullable=False, comment='关联的缺陷阶段ID'),
    sa.Column('source_data_ids', sa.JSON(), nullable=False, comment='源数据ID集合'),
    sa.Column('evaluation_method', sa.Enum('AUTO', 'MANUAL', name='evaluationmethod'), nullable=True, comment='评分方式'),
    sa.Column('ai_suggestion', sa.Text(), nullable=True, comment='AI评估建议'),
    sa.Column('ai_score', sa.Integer(), nullable=True, comment='AI评估分数'),
    sa.Column('combine_time', sa.DateTime(), nullable=True, comment='合并时间'),
    sa.ForeignKeyConstraint(['defect_id'], ['defects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['defect_stage_id'], ['defect_stages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('defect_stage_combine_records', schema=None) as batch_op:
        batch_op.create_index('ix_combine_records_defect_id', ['defect_id'], unique=False)
        batch_op.create_index('ix_combine_records_defect_stage_id', ['defect_stage_id'], unique=False)

    op.create_table('defect_flow_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='历史记录ID，主键'),
    sa.Column('defect_id', sa.Integer(), nullable=False, comment='关联的缺陷ID'),
    sa.Column('from_stage_id', sa.Integer(), nullable=True, comment='源阶段ID'),
    sa.Column('to_stage_id', sa.Integer(), nullable=False, comment='目标阶段ID'),
    sa.Column('action_type', sa.Enum('CREATE', 'UPDATE', 'APPROVE', 'REJECT', 'TRANSFER', 'ASSIGN_DIVISION', 'SUBMIT_SOLUTION', 'REMIND', name='actiontype'), nullable=False, comment='操作类型'),
    sa.Column('reminder_id', sa.Integer(), nullable=True, comment='关联的跟催记录ID'),
    sa.Column('action_by', sa.Integer(), nullable=False, comment='操作人ID'),
    sa.Column('action_time', sa.DateTime(), nullable=True, comment='操作时间'),
    sa.Column('notes', sa.Text(), nullable=True, comment='操作备注'),
    sa.ForeignKeyConstraint(['action_by'], ['user.user_id'], ),
    sa.ForeignKeyConstraint(['defect_id'], ['defects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['from_stage_id'], ['defect_stages.id'], ),
    sa.ForeignKeyConstraint(['reminder_id'], ['defect_reminders.id'], ),
    sa.ForeignKeyConstraint(['to_stage_id'], ['defect_stages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('defect_flow_history', schema=None) as batch_op:
        batch_op.create_index('ix_flow_history_action_by', ['action_by'], unique=False)
        batch_op.create_index('ix_flow_history_action_time', ['action_time'], unique=False)
        batch_op.create_index('ix_flow_history_defect_id', ['defect_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('defect_flow_history', schema=None) as batch_op:
        batch_op.drop_index('ix_flow_history_defect_id')
        batch_op.drop_index('ix_flow_history_action_time')
        batch_op.drop_index('ix_flow_history_action_by')

    op.drop_table('defect_flow_history')
    with op.batch_alter_table('defect_stage_combine_records', schema=None) as batch_op:
        batch_op.drop_index('ix_combine_records_defect_stage_id')
        batch_op.drop_index('ix_combine_records_defect_id')

    op.drop_table('defect_stage_combine_records')
    with op.batch_alter_table('defect_reminders', schema=None) as batch_op:
        batch_op.drop_index('ix_reminders_reminder_type')
        batch_op.drop_index('ix_reminders_reminder_by')
        batch_op.drop_index('ix_reminders_defect_stage_id')
        batch_op.drop_index('ix_reminders_defect_id')

    op.drop_table('defect_reminders')
    with op.batch_alter_table('defect_rejections', schema=None) as batch_op:
        batch_op.drop_index('ix_rejections_rejected_by')
        batch_op.drop_index('ix_rejections_defect_stage_id')
        batch_op.drop_index('ix_rejections_defect_id')

    op.drop_table('defect_rejections')
    with op.batch_alter_table('defects', schema=None) as batch_op:
        batch_op.drop_index('ix_defects_version_id')
        batch_op.drop_index('ix_defects_status')
        batch_op.drop_index('ix_defects_project_id')
        batch_op.drop_index('ix_defects_current_stage_id')
        batch_op.drop_index('ix_defects_creator_id')

    op.drop_table('defects')
    with op.batch_alter_table('defect_stage_data', schema=None) as batch_op:
        batch_op.drop_index('ix_stage_data_submitted_by')
        batch_op.drop_index('ix_stage_data_defect_stage_id')
        batch_op.drop_index('ix_stage_data_data_type')

    op.drop_table('defect_stage_data')
    with op.batch_alter_table('defect_stage_collaborators', schema=None) as batch_op:
        batch_op.drop_index('ix_collaborators_user_id')
        batch_op.drop_index('ix_collaborators_defect_stage_id')

    op.drop_table('defect_stage_collaborators')
    with op.batch_alter_table('defect_locale_invitations', schema=None) as batch_op:
        batch_op.drop_index('ix_invitations_status')
        batch_op.drop_index('ix_invitations_invitee_id')
        batch_op.drop_index('ix_invitations_defect_stage_id')

    op.drop_table('defect_locale_invitations')
    with op.batch_alter_table('defect_analysis_divisions', schema=None) as batch_op:
        batch_op.drop_index('ix_divisions_defect_stage_id')
        batch_op.drop_index('ix_divisions_assignee_id')

    op.drop_table('defect_analysis_divisions')
    with op.batch_alter_table('defect_stages', schema=None) as batch_op:
        batch_op.drop_index('ix_defect_stages_status')
        batch_op.drop_index('ix_defect_stages_assigned_to')

    op.drop_table('defect_stages')
    # ### end Alembic commands ###
