"""modify_defect_tables_0831

Revision ID: 1fdb0f95d2ef
Revises: 71f60f0233d9
Create Date: 2025-08-31 11:50:19.953233

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1fdb0f95d2ef'
down_revision = '71f60f0233d9'
branch_labels = None
depends_on = None


def upgrade():
    # 已在app 中执行过 # 创建所有缺失的表
    #     db.create_all()
    pass
    # ### commands auto generated by Alembic - please adjust! ###

    # ### end Alembic commands ###


    # ### end Alembic commands ###
