"""delete UniqueConstraint for defect_stage_data

Revision ID: 29da68ed93e4
Revises: bb699c3552d3
Create Date: 2025-09-03 19:03:50.941097

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '29da68ed93e4'
down_revision = 'bb699c3552d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('defect_stage_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('uk_stage_data_type'))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('defect_stage_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uk_stage_data_type'), ['defect_stage_id', 'data_type', 'is_current'], unique=True)
    # ### end Alembic commands ###
