"""Add three new models

Revision ID: 397b68e65776
Revises: 3dfec0434f8f
Create Date: 2025-08-28 10:52:21.592436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '397b68e65776'
down_revision = '3dfec0434f8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('template_type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='模板类型ID，主键自增长'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='模板类型名称（如"缺陷描述"、"回归测试"）'),
    sa.Column('description', sa.Text(), nullable=True, comment='模板类型详细描述'),
    sa.Column('created_time', sa.TIMESTAMP(), nullable=True, comment='记录创建时间'),
    sa.Column('updated_time', sa.TIMESTAMP(), nullable=True, comment='记录最后更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('template',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='模板ID，主键自增长'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='关联的用户ID，外键关联user表'),
    sa.Column('type_id', sa.Integer(), nullable=False, comment='模板类型ID，外键关联template_type表'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='模板名称'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='模板启用状态：1-启用，0-禁用'),
    sa.Column('created_by', sa.Integer(), nullable=False, comment='创建者用户ID，关联用户表'),
    sa.Column('updated_by', sa.Integer(), nullable=True, comment='最后更新者用户ID，关联用户表'),
    sa.Column('created_time', sa.TIMESTAMP(), nullable=True, comment='记录创建时间'),
    sa.Column('updated_time', sa.TIMESTAMP(), nullable=True, comment='记录最后更新时间'),
    sa.ForeignKeyConstraint(['type_id'], ['template_type.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('template_item',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='模板项ID，主键自增长'),
    sa.Column('template_id', sa.Integer(), nullable=False, comment='所属模板ID，外键关联template表'),
    sa.Column('item_type', sa.Enum('title', 'description', name='item_type_enum'), nullable=False, comment='项类型：title-标题，description-描述'),
    sa.Column('content', sa.Text(), nullable=True, comment='项内容'),
    sa.Column('sort_order', sa.Integer(), nullable=True, comment='排序顺序，数值越小越靠前'),
    sa.Column('is_removable', sa.Boolean(), nullable=True, comment='是否可移除：1-可移除，0-不可移除'),
    sa.Column('is_required', sa.Boolean(), nullable=True, comment='是否必填：1-必填，0-可选'),
    sa.Column('created_time', sa.TIMESTAMP(), nullable=True, comment='记录创建时间'),
    sa.Column('updated_time', sa.TIMESTAMP(), nullable=True, comment='记录最后更新时间'),
    sa.ForeignKeyConstraint(['template_id'], ['template.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('template_item')
    op.drop_table('template')
    op.drop_table('template_type')
    # ### end Alembic commands ###
