"""add_defect_tables_foreign_key

Revision ID: 3a5ac92d784e
Revises: 1ad37ce49f1d
Create Date: 2025-08-30 13:00:36.329295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a5ac92d784e'
down_revision = '1ad37ce49f1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('defect_stages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('defect_id', sa.Integer(), nullable=False, comment='关联的缺陷ID'))
        batch_op.add_column(sa.Column('stage_type', sa.String(length=50), nullable=False, comment='阶段类型'))
        batch_op.add_column(sa.Column('previous_stage_id', sa.Integer(), nullable=True, comment='上一阶段ID'))
        batch_op.create_index('ix_defect_stages_defect_id', ['defect_id'], unique=False)
        batch_op.create_index('ix_defect_stages_stage_type', ['stage_type'], unique=False)
        batch_op.create_foreign_key(None, 'defects', ['defect_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'defect_stage_types', ['stage_type'], ['stage_key'])
        batch_op.create_foreign_key(None, 'defect_stages', ['previous_stage_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('defect_stages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index('ix_defect_stages_stage_type')
        batch_op.drop_index('ix_defect_stages_defect_id')
        batch_op.drop_column('previous_stage_id')
        batch_op.drop_column('stage_type')
        batch_op.drop_column('defect_id')

    # ### end Alembic commands ###
