"""Add three new models

Revision ID: 3dfec0434f8f
Revises: fc5b87daa39b
Create Date: 2025-08-28 09:24:02.082916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3dfec0434f8f'
down_revision = 'fc5b87daa39b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modification_log', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('modification_log_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'defect_level', ['defect_level_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modification_log', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('modification_log_ibfk_1'), 'defect_level', ['defect_level_id'], ['id'])

    # ### end Alembic commands ###
