"""DefectFlowHistory add ai_sug_score_id

Revision ID: 42055c058668
Revises: 9cf38444077f
Create Date: 2025-11-03 18:14:31.885240

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '42055c058668'
down_revision = '9cf38444077f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('defect_flow_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_sug_score_id', sa.String(length=128), nullable=True, comment='关联的AI建议评分ID'))
        batch_op.create_index('ix_flow_history_ai_sug_score_id', ['ai_sug_score_id'], unique=False)
        batch_op.create_foreign_key(None, 'ai_sug_score', ['ai_sug_score_id'], ['id'])

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('defect_flow_history', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index('ix_flow_history_ai_sug_score_id')
        batch_op.drop_column('ai_sug_score_id')

    # ### end Alembic commands ###
