"""tech_groups  product_lines add user_id

Revision ID: 534870ad825d
Revises: 81ce417c050c
Create Date: 2025-09-15 12:03:11.687970

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '534870ad825d'
down_revision = '81ce417c050c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('defect_solution_divisions', schema=None) as batch_op:
        batch_op.alter_column('version',
               existing_type=mysql.VARCHAR(length=100),
               comment='版本信息，非必填',
               existing_comment='版本信息',
               existing_nullable=True)

    with op.batch_alter_table('product_lines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['user_id'])

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_line_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('code', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('created_time', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint('unique_product_name_per_line', ['product_line_id', 'name'])
        batch_op.create_unique_constraint(None, ['code'])
        batch_op.create_foreign_key(None, 'product_lines', ['product_line_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('tech_groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['user_id'])
        batch_op.drop_column('leader_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###


    with op.batch_alter_table('tech_groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('leader_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint('unique_product_name_per_line', type_='unique')
        batch_op.drop_column('created_time')
        batch_op.drop_column('is_active')
        batch_op.drop_column('description')
        batch_op.drop_column('code')
        batch_op.drop_column('name')
        batch_op.drop_column('product_line_id')

    with op.batch_alter_table('product_lines', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')



    with op.batch_alter_table('defect_solution_divisions', schema=None) as batch_op:
        batch_op.alter_column('version',
               existing_type=mysql.VARCHAR(length=100),
               comment='版本信息',
               existing_comment='版本信息，非必填',
               existing_nullable=True)

    # ### end Alembic commands ###
