"""Defect add defect_type

Revision ID: 5af300e2363d
Revises: 42055c058668
Create Date: 2025-11-10 18:28:03.191924

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5af300e2363d'
down_revision = '42055c058668'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('defects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('defect_type', sa.String(length=50), nullable=True, comment='simplified-简化版'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('defects', schema=None) as batch_op:
        batch_op.drop_column('defect_type')
    # ### end Alembic commands ###
