"""Add three new models

Revision ID: 608e23631437
Revises: cad7403c1a00
Create Date: 2025-08-27 15:00:30.061621

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '608e23631437'
down_revision = 'cad7403c1a00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('defect_level', schema=None) as batch_op:
        batch_op.add_column(sa.Column('critical_defects', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('major_defects', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('minor_defects', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('suggestion_defects', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.drop_index(batch_op.f('level_name'))
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['user_id'], ondelete='CASCADE')
        batch_op.drop_column('level_name')
        batch_op.drop_column('score')

    with op.batch_alter_table('modification_log', schema=None) as batch_op:
        batch_op.alter_column('old_value',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('new_value',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.Float(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modification_log', schema=None) as batch_op:
        batch_op.alter_column('new_value',
               existing_type=sa.Float(),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('old_value',
               existing_type=sa.Float(),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)

    with op.batch_alter_table('defect_level', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score', mysql.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('level_name', mysql.VARCHAR(length=50), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index(batch_op.f('level_name'), ['level_name'], unique=True)
        batch_op.drop_column('user_id')
        batch_op.drop_column('suggestion_defects')
        batch_op.drop_column('minor_defects')
        batch_op.drop_column('major_defects')
        batch_op.drop_column('critical_defects')

    # ### end Alembic commands ###
