"""table defects modify Enum field type to String

Revision ID: 6114121f5c4c
Revises: c48e20265398
Create Date: 2025-09-01 17:32:09.866281

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6114121f5c4c'
down_revision = 'c48e20265398'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('defect_locale_invitations', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('PENDING', 'ACCEPTED', 'REJECTED', 'CANCELLED'),
               type_=sa.String(length=50),
               existing_comment='邀请状态',
               existing_nullable=True)

    with op.batch_alter_table('defect_rejections', schema=None) as batch_op:
        batch_op.alter_column('rejection_type',
               existing_type=mysql.ENUM('STAGE', 'INVITATION', 'ANALYSIS', 'SOLUTION'),
               type_=sa.String(length=50),
               existing_comment='驳回类型',
               existing_nullable=False)

    with op.batch_alter_table('defect_reminders', schema=None) as batch_op:
        batch_op.alter_column('reminder_type',
               existing_type=mysql.ENUM('ANALYSIS', 'SOLUTION'),
               type_=sa.String(length=50),
               existing_comment='跟催类型',
               existing_nullable=False)
        batch_op.alter_column('reminder_status',
               existing_type=mysql.ENUM('SENT', 'VIEWED', 'ACTED'),
               type_=sa.String(length=50),
               existing_comment='跟催状态',
               existing_nullable=True)

    with op.batch_alter_table('defect_stage_collaborators', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=mysql.ENUM('PRIMARY', 'COLLABORATOR'),
               type_=sa.String(length=50),
               existing_comment='协作者角色',
               existing_nullable=True)

    with op.batch_alter_table('defect_stage_combine_records', schema=None) as batch_op:
        batch_op.alter_column('evaluation_method',
               existing_type=mysql.ENUM('AUTO', 'MANUAL'),
               type_=sa.String(length=50),
               existing_comment='评分方式',
               existing_nullable=True)

    with op.batch_alter_table('defect_stage_data', schema=None) as batch_op:
        batch_op.alter_column('data_type',
               existing_type=mysql.ENUM('DEFECT_DESCRIPTION', 'CAUSE_ANALYSIS', 'SOLUTION', 'TEST_RESULT'),
               type_=sa.String(length=50),
               existing_comment='数据类型，对应问题描述、原因分析、解决措施及验证4个特殊阶段',
               existing_nullable=False)
        batch_op.alter_column('evaluation_method',
               existing_type=mysql.ENUM('AUTO', 'MANUAL'),
               type_=sa.String(length=50),
               existing_comment='评分方式',
               existing_nullable=True)

    with op.batch_alter_table('defect_stages', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('IN_PROGRESS', 'COMPLETED', 'REJECTED', 'CANCELLED'),
               type_=sa.String(length=50),
               existing_comment='阶段状态',
               existing_nullable=True)

    with op.batch_alter_table('defects', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('DRAFT', 'OPEN', 'RESOLVED', 'CLOSED', 'REJECTED'),
               type_=sa.String(length=50),
               existing_comment='缺陷整体状态',
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('defects', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=50),
               type_=mysql.ENUM('DRAFT', 'OPEN', 'RESOLVED', 'CLOSED', 'REJECTED'),
               existing_comment='缺陷整体状态',
               existing_nullable=True)

    with op.batch_alter_table('defect_stages', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=50),
               type_=mysql.ENUM('IN_PROGRESS', 'COMPLETED', 'REJECTED', 'CANCELLED'),
               existing_comment='阶段状态',
               existing_nullable=True)

    with op.batch_alter_table('defect_stage_data', schema=None) as batch_op:
        batch_op.alter_column('evaluation_method',
               existing_type=sa.String(length=50),
               type_=mysql.ENUM('AUTO', 'MANUAL'),
               existing_comment='评分方式',
               existing_nullable=True)
        batch_op.alter_column('data_type',
               existing_type=sa.String(length=50),
               type_=mysql.ENUM('DEFECT_DESCRIPTION', 'CAUSE_ANALYSIS', 'SOLUTION', 'TEST_RESULT'),
               existing_comment='数据类型，对应问题描述、原因分析、解决措施及验证4个特殊阶段',
               existing_nullable=False)

    with op.batch_alter_table('defect_stage_combine_records', schema=None) as batch_op:
        batch_op.alter_column('evaluation_method',
               existing_type=sa.String(length=50),
               type_=mysql.ENUM('AUTO', 'MANUAL'),
               existing_comment='评分方式',
               existing_nullable=True)

    with op.batch_alter_table('defect_stage_collaborators', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.String(length=50),
               type_=mysql.ENUM('PRIMARY', 'COLLABORATOR'),
               existing_comment='协作者角色',
               existing_nullable=True)

    with op.batch_alter_table('defect_reminders', schema=None) as batch_op:
        batch_op.alter_column('reminder_status',
               existing_type=sa.String(length=50),
               type_=mysql.ENUM('SENT', 'VIEWED', 'ACTED'),
               existing_comment='跟催状态',
               existing_nullable=True)
        batch_op.alter_column('reminder_type',
               existing_type=sa.String(length=50),
               type_=mysql.ENUM('ANALYSIS', 'SOLUTION'),
               existing_comment='跟催类型',
               existing_nullable=False)

    with op.batch_alter_table('defect_rejections', schema=None) as batch_op:
        batch_op.alter_column('rejection_type',
               existing_type=sa.String(length=50),
               type_=mysql.ENUM('STAGE', 'INVITATION', 'ANALYSIS', 'SOLUTION'),
               existing_comment='驳回类型',
               existing_nullable=False)

    with op.batch_alter_table('defect_locale_invitations', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=50),
               type_=mysql.ENUM('PENDING', 'ACCEPTED', 'REJECTED', 'CANCELLED'),
               existing_comment='邀请状态',
               existing_nullable=True)

    with op.batch_alter_table('defect_flow_history', schema=None) as batch_op:
        batch_op.alter_column('action_type',
               existing_type=sa.String(length=50),
               type_=mysql.ENUM('CREATE', 'UPDATE', 'APPROVE', 'INVITE_TO_ANALYZE', 'REJECT', 'TRANSFER', 'ASSIGN_DIVISION', 'SUBMIT_SOLUTION', 'REMIND'),
               existing_comment='操作类型',
               existing_nullable=False)

    # ### end Alembic commands ###
