"""products code not unique

Revision ID: 6220dbf972a1
Revises: 83e542469a20
Create Date: 2025-09-23 11:53:49.981869

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6220dbf972a1'
down_revision = '83e542469a20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('code'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('code'), ['code'], unique=True)
    # ### end Alembic commands ###
