"""modify_defect_tables

Revision ID: 71f60f0233d9
Revises: adf24d96bda4
Create Date: 2025-08-30 23:16:01.958174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71f60f0233d9'
down_revision = 'adf24d96bda4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('defects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('defect_number', sa.String(length=64), autoincrement=False, nullable=True, comment='缺陷单号，唯一，例如 202508191024'))
        batch_op.add_column(sa.Column('defect_reproducibility', sa.String(length=50), nullable=False, comment='缺陷重现概率'))

    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('user_roles_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'roles', ['role_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('user_roles_ibfk_1'), 'roles', ['role_id'], ['id'])

    with op.batch_alter_table('defects', schema=None) as batch_op:
        batch_op.drop_column('defect_reproducibility')
        batch_op.drop_column('defect_number')

    # ### end Alembic commands ###
