"""defect_solution_divisions update

Revision ID: 81ce417c050c
Revises: a5162619436a
Create Date: 2025-09-07 10:35:22.023611

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '81ce417c050c'
down_revision = 'a5162619436a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('defect_solution_divisions', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['assign_by_id'], ['user_id'])


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('defect_solution_divisions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
