"""user_roles add version_id project_id field

Revision ID: 83e542469a20
Revises: 6da3d3c987e7
Create Date: 2025-09-22 16:56:01.639686

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '83e542469a20'
down_revision = '6da3d3c987e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version_id', sa.Integer(), nullable=True, comment='关联版本ID'))
        batch_op.add_column(sa.Column('project_id', sa.Integer(), nullable=True, comment='关联项目ID'))
        batch_op.create_foreign_key(None, 'versions', ['version_id'], ['id'])
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('project_id')
        batch_op.drop_column('version_id')
    # ### end Alembic commands ###
