"""Add three new models

Revision ID: a0976ca4d845
Revises: 621179d8f8a1
Create Date: 2025-08-27 09:45:28.988983

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a0976ca4d845'
down_revision = '621179d8f8a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('defect_level',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level_name', sa.String(length=50), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('level_name')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('modification_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('defect_level_id', sa.Integer(), nullable=False),
    sa.Column('modifier', sa.String(length=50), nullable=False),
    sa.Column('field_name', sa.String(length=50), nullable=False),
    sa.Column('old_value', sa.String(length=100), nullable=False),
    sa.Column('new_value', sa.String(length=100), nullable=False),
    sa.Column('modified_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['defect_level_id'], ['defect_level.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_rights', schema=None) as batch_op:
        batch_op.alter_column('menu',
               existing_type=mysql.TINYINT(display_width=4),
               type_=sa.Integer(),
               comment=None,
               existing_comment='1是menu，0不是',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('admin_user', schema=None) as batch_op:
        batch_op.alter_column('is_delete',
               existing_type=mysql.TINYINT(display_width=4),
               type_=sa.Integer(),
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('ai_sug_score', schema=None) as batch_op:
        batch_op.alter_column('state',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='0：暂存\r\n1：已评估\r\n-1：批量评估中\r\n-2：评估中\r\n-3：评估失败，请求超时\r\n-4：返回数据错误',
               existing_nullable=True)
        batch_op.alter_column('is_delete',
               existing_type=mysql.TINYINT(display_width=4),
               type_=sa.Integer(),
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('is_admin_delete',
               existing_type=mysql.TINYINT(display_width=4),
               type_=sa.Integer(),
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('error_mess',
               existing_type=mysql.TEXT(collation='utf8mb4_bin'),
               comment=None,
               existing_comment='失败原因',
               existing_nullable=True)
        batch_op.alter_column('model_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_bin', length=64),
               comment=None,
               existing_comment='模型名称',
               existing_nullable=True)
        batch_op.alter_column('create_time',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('update_time',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
        batch_op.drop_index(batch_op.f('user_id+admin_user_id'))
        batch_op.drop_table_comment(
        existing_comment='缺陷、产品表'
    )

    with op.batch_alter_table('ai_sug_score_2', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summarize_val_sug', sa.Text(), nullable=True))
        batch_op.alter_column('file_key',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='阿里云oss路径',
               existing_nullable=True)
        batch_op.alter_column('file_name',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='附件名称，文件名',
               existing_nullable=True)
        batch_op.alter_column('title',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='主题',
               existing_nullable=True)
        batch_op.alter_column('select_1',
               existing_type=mysql.TINYINT(display_width=255),
               type_=sa.Integer(),
               comment=None,
               existing_comment='立项-立项的驱动源：\r\n0：重大项目机会驱动型立项\r\n1：市场机会/威胁分析驱动型立项\r\n2：市场机会/威胁分析+重大项目机会双驱动型立项\r\n3：战略制高点/瓶颈点争夺型立项',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('select_2',
               existing_type=mysql.TINYINT(display_width=255),
               type_=sa.Integer(),
               comment=None,
               existing_comment='立项-项目发展阶段:\r\n0-首次\r\n1-迭代升级',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('total_score',
               existing_type=mysql.DECIMAL(precision=4, scale=1),
               comment=None,
               existing_comment='总评分',
               existing_nullable=True)
        batch_op.alter_column('case',
               existing_type=mysql.TINYINT(display_width=4),
               type_=sa.Integer(),
               comment=None,
               existing_comment='阶段：0,1,2,3',
               existing_nullable=True)
        batch_op.alter_column('all_markdwon_text',
               existing_type=mysql.LONGTEXT(),
               comment=None,
               existing_comment='转化后的全文',
               existing_nullable=True)
        batch_op.alter_column('summarize_text',
               existing_type=mysql.TEXT(),
               comment=None,
               existing_comment='文档总结-文档摘要',
               existing_nullable=True)
        batch_op.alter_column('xmind_json',
               existing_type=mysql.TEXT(),
               comment=None,
               existing_comment='思维导图json',
               existing_nullable=True)
        batch_op.alter_column('state',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='0：文件已传到阿里云本地',
               existing_nullable=True)
        batch_op.alter_column('is_delete',
               existing_type=mysql.TINYINT(display_width=4),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('is_admin_delete',
               existing_type=mysql.TINYINT(display_width=4),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('create_time',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('update_time',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
        batch_op.drop_table_comment(
        existing_comment='立项表'
    )

    with op.batch_alter_table('cammand', schema=None) as batch_op:
        batch_op.alter_column('type_child',
               existing_type=mysql.TINYINT(display_width=4),
               type_=sa.Integer(),
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('doc_files', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=mysql.TINYINT(display_width=11),
               type_=sa.Integer(),
               comment=None,
               existing_comment='根分级\r\n0：缺陷-671b\r\n1：需求-617b\r\n2：立项\r\n100:缺陷-小模型\r\n101-需求-小模型',
               existing_nullable=True)
        batch_op.alter_column('markdown',
               existing_type=mysql.LONGTEXT(collation='utf8mb4_bin'),
               comment=None,
               existing_comment='评估规则文档html(缺陷、需求、立项)',
               existing_nullable=True)
        batch_op.alter_column('html',
               existing_type=mysql.LONGTEXT(collation='utf8mb4_bin'),
               comment=None,
               existing_comment='评估规则文档markdown(缺陷、需求、立项)',
               existing_nullable=True)
        batch_op.alter_column('html_content',
               existing_type=mysql.LONGTEXT(collation='utf8mb4_bin'),
               comment=None,
               existing_comment='立项xx内容总结规则',
               existing_nullable=True)
        batch_op.alter_column('markdown_content',
               existing_type=mysql.LONGTEXT(collation='utf8mb4_bin'),
               comment=None,
               existing_comment='立项xx内容总结规则',
               existing_nullable=True)
        batch_op.alter_column('cammand',
               existing_type=mysql.TEXT(collation='utf8mb4_bin'),
               comment=None,
               existing_comment='命令',
               existing_nullable=True)
        batch_op.alter_column('title_show',
               existing_type=mysql.VARCHAR(collation='utf8mb4_bin', length=255),
               comment=None,
               existing_comment='显示标题',
               existing_nullable=True,
               existing_server_default=sa.text("''"))
        batch_op.alter_column('big_title_show',
               existing_type=mysql.VARCHAR(collation='utf8mb4_bin', length=255),
               comment=None,
               existing_comment='显示大标题',
               existing_nullable=True)
        batch_op.alter_column('child_type_1',
               existing_type=mysql.TINYINT(display_width=4),
               type_=sa.Integer(),
               comment=None,
               existing_comment='第一子分级',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('child_type_2',
               existing_type=mysql.TINYINT(display_width=4),
               type_=sa.Integer(),
               comment=None,
               existing_comment='第二子分级',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('step',
               existing_type=mysql.TINYINT(display_width=4),
               type_=sa.Integer(),
               comment=None,
               existing_comment='标记哪一个step，和ai_sug_score.step对应',
               existing_nullable=True,
               existing_server_default=sa.text("'-1'"))

    with op.batch_alter_table('email_queue', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.TINYINT(display_width=4),
               type_=sa.Integer(),
               comment=None,
               existing_comment='0',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('create_time',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('update_time',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))

    with op.batch_alter_table('email_user_right', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('type_0',
               existing_type=mysql.TINYINT(display_width=4),
               type_=sa.Integer(),
               comment=None,
               existing_comment='0:缺陷管理',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('type_1',
               existing_type=mysql.TINYINT(display_width=4),
               type_=sa.Integer(),
               comment=None,
               existing_comment='1:需求管理',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('type_2',
               existing_type=mysql.TINYINT(display_width=4),
               type_=sa.Integer(),
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('create_time',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('update_time',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))

    with op.batch_alter_table('mobile_user_right', schema=None) as batch_op:
        batch_op.alter_column('user_total_num',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='可邀同事总数',
               existing_nullable=True,
               existing_server_default=sa.text("'10'"))
        batch_op.alter_column('remind_invited_num',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='剩余几次发短信提醒',
               existing_nullable=True,
               existing_server_default=sa.text("'-1'"))
        batch_op.alter_column('request_num',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='可提问总次数',
               existing_nullable=True,
               existing_server_default=sa.text("'10'"))
        batch_op.alter_column('remind_date',
               existing_type=mysql.BIGINT(display_width=20),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('sended_remind_date_message',
               existing_type=mysql.TINYINT(display_width=4),
               type_=sa.Integer(),
               comment=None,
               existing_comment='是否已发到期短信',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('sended_remind_invite_message',
               existing_type=mysql.TINYINT(display_width=4),
               type_=sa.Integer(),
               comment=None,
               existing_comment='用于控制是否发短信',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('sended_remind_request_message',
               existing_type=mysql.TINYINT(display_width=4),
               type_=sa.Integer(),
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('type',
               existing_type=mysql.TINYINT(display_width=4),
               type_=sa.Integer(),
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('state',
               existing_type=mysql.TINYINT(display_width=4),
               type_=sa.Integer(),
               comment=None,
               existing_comment='0为试用状态',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('remind_invited_open',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Integer(),
               comment=None,
               existing_comment='是否开启发短信 0未开，1已开',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('remind_request_open',
               existing_type=mysql.TINYINT(display_width=4),
               type_=sa.Integer(),
               comment=None,
               existing_comment='0未开，1已开',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('remind_date_open',
               existing_type=mysql.TINYINT(display_width=4),
               type_=sa.Integer(),
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('admin_last_update',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('create_time',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('update_time',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))

    with op.batch_alter_table('module_to_model', schema=None) as batch_op:
        batch_op.alter_column('module',
               existing_type=mysql.TINYINT(display_width=64),
               type_=sa.Integer(),
               comment=None,
               existing_comment='0:缺陷',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('model_id',
               existing_type=mysql.TINYINT(display_width=4),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('create_time',
               existing_type=mysql.DATETIME(),
               nullable=False)
        batch_op.alter_column('update_time',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('sms_queue', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=mysql.TINYINT(display_width=4),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('e1',
               existing_type=mysql.TINYINT(display_width=4),
               type_=sa.Integer(),
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('e2',
               existing_type=mysql.TINYINT(display_width=4),
               type_=sa.Integer(),
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('send_num',
               existing_type=mysql.TINYINT(display_width=4),
               type_=sa.Integer(),
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('create_time',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('update_time',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))

    with op.batch_alter_table('upload_files', schema=None) as batch_op:
        batch_op.alter_column('create_time',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('update_time',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('company_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_bin', length=255),
               comment=None,
               existing_comment='公司名',
               existing_nullable=True,
               existing_server_default=sa.text("''"))
        batch_op.alter_column('employees_num',
               existing_type=mysql.VARCHAR(collation='utf8mb4_bin', length=11),
               comment=None,
               existing_comment='员工数',
               existing_nullable=True)
        batch_op.alter_column('sense',
               existing_type=mysql.VARCHAR(collation='utf8mb4_bin', length=255),
               comment=None,
               existing_comment='场景',
               existing_nullable=True)
        batch_op.alter_column('position',
               existing_type=mysql.VARCHAR(collation='utf8mb4_bin', length=255),
               comment=None,
               existing_comment='职位',
               existing_nullable=True)
        batch_op.alter_column('dept',
               existing_type=mysql.VARCHAR(collation='utf8mb4_bin', length=255),
               comment=None,
               existing_comment='部门',
               existing_nullable=True,
               existing_server_default=sa.text("''"))
        batch_op.alter_column('status',
               existing_type=mysql.TINYINT(display_width=4),
               type_=sa.Integer(),
               comment=None,
               existing_comment='手机用户，0：刚填写手机密码；1：注册完填写完公司\r\n\r\n邮件用户，0未邮箱激活，1已激活',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('is_delete',
               existing_type=mysql.TINYINT(display_width=4),
               type_=sa.Integer(),
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('create_time',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('update_time',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))

    with op.batch_alter_table('val_ai_aq', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=mysql.TINYINT(display_width=4),
               type_=sa.Integer(),
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('create_time',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('update_time',
               existing_type=mysql.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('val_ai_aq', schema=None) as batch_op:
        batch_op.alter_column('update_time',
               existing_type=mysql.DATETIME(),
               nullable=True)
        batch_op.alter_column('create_time',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('type',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=4),
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('update_time',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
        batch_op.alter_column('create_time',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('is_delete',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=4),
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('status',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=4),
               comment='手机用户，0：刚填写手机密码；1：注册完填写完公司\r\n\r\n邮件用户，0未邮箱激活，1已激活',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('dept',
               existing_type=mysql.VARCHAR(collation='utf8mb4_bin', length=255),
               comment='部门',
               existing_nullable=True,
               existing_server_default=sa.text("''"))
        batch_op.alter_column('position',
               existing_type=mysql.VARCHAR(collation='utf8mb4_bin', length=255),
               comment='职位',
               existing_nullable=True)
        batch_op.alter_column('sense',
               existing_type=mysql.VARCHAR(collation='utf8mb4_bin', length=255),
               comment='场景',
               existing_nullable=True)
        batch_op.alter_column('employees_num',
               existing_type=mysql.VARCHAR(collation='utf8mb4_bin', length=11),
               comment='员工数',
               existing_nullable=True)
        batch_op.alter_column('company_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_bin', length=255),
               comment='公司名',
               existing_nullable=True,
               existing_server_default=sa.text("''"))

    with op.batch_alter_table('upload_files', schema=None) as batch_op:
        batch_op.alter_column('update_time',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
        batch_op.alter_column('create_time',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('sms_queue', schema=None) as batch_op:
        batch_op.alter_column('update_time',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
        batch_op.alter_column('create_time',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('send_num',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=4),
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('e2',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=4),
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('e1',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=4),
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('type',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=4),
               existing_nullable=True)

    with op.batch_alter_table('module_to_model', schema=None) as batch_op:
        batch_op.alter_column('update_time',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('create_time',
               existing_type=mysql.DATETIME(),
               nullable=True)
        batch_op.alter_column('model_id',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=4),
               existing_nullable=True)
        batch_op.alter_column('module',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=64),
               comment='0:缺陷',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('mobile_user_right', schema=None) as batch_op:
        batch_op.alter_column('update_time',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
        batch_op.alter_column('create_time',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('admin_last_update',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('remind_date_open',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=4),
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('remind_request_open',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=4),
               comment='0未开，1已开',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('remind_invited_open',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=1),
               comment='是否开启发短信 0未开，1已开',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('state',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=4),
               comment='0为试用状态',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('type',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=4),
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('sended_remind_request_message',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=4),
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('sended_remind_invite_message',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=4),
               comment='用于控制是否发短信',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('sended_remind_date_message',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=4),
               comment='是否已发到期短信',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('remind_date',
               existing_type=sa.DateTime(),
               type_=mysql.BIGINT(display_width=20),
               existing_nullable=True)
        batch_op.alter_column('request_num',
               existing_type=mysql.INTEGER(display_width=11),
               comment='可提问总次数',
               existing_nullable=True,
               existing_server_default=sa.text("'10'"))
        batch_op.alter_column('remind_invited_num',
               existing_type=mysql.INTEGER(display_width=11),
               comment='剩余几次发短信提醒',
               existing_nullable=True,
               existing_server_default=sa.text("'-1'"))
        batch_op.alter_column('user_total_num',
               existing_type=mysql.INTEGER(display_width=11),
               comment='可邀同事总数',
               existing_nullable=True,
               existing_server_default=sa.text("'10'"))

    with op.batch_alter_table('email_user_right', schema=None) as batch_op:
        batch_op.alter_column('update_time',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
        batch_op.alter_column('create_time',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('type_2',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=4),
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('type_1',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=4),
               comment='1:需求管理',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('type_0',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=4),
               comment='0:缺陷管理',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('email_queue', schema=None) as batch_op:
        batch_op.alter_column('update_time',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
        batch_op.alter_column('create_time',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('status',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=4),
               comment='0',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('doc_files', schema=None) as batch_op:
        batch_op.alter_column('step',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=4),
               comment='标记哪一个step，和ai_sug_score.step对应',
               existing_nullable=True,
               existing_server_default=sa.text("'-1'"))
        batch_op.alter_column('child_type_2',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=4),
               comment='第二子分级',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('child_type_1',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=4),
               comment='第一子分级',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('big_title_show',
               existing_type=mysql.VARCHAR(collation='utf8mb4_bin', length=255),
               comment='显示大标题',
               existing_nullable=True)
        batch_op.alter_column('title_show',
               existing_type=mysql.VARCHAR(collation='utf8mb4_bin', length=255),
               comment='显示标题',
               existing_nullable=True,
               existing_server_default=sa.text("''"))
        batch_op.alter_column('cammand',
               existing_type=mysql.TEXT(collation='utf8mb4_bin'),
               comment='命令',
               existing_nullable=True)
        batch_op.alter_column('markdown_content',
               existing_type=mysql.LONGTEXT(collation='utf8mb4_bin'),
               comment='立项xx内容总结规则',
               existing_nullable=True)
        batch_op.alter_column('html_content',
               existing_type=mysql.LONGTEXT(collation='utf8mb4_bin'),
               comment='立项xx内容总结规则',
               existing_nullable=True)
        batch_op.alter_column('html',
               existing_type=mysql.LONGTEXT(collation='utf8mb4_bin'),
               comment='评估规则文档markdown(缺陷、需求、立项)',
               existing_nullable=True)
        batch_op.alter_column('markdown',
               existing_type=mysql.LONGTEXT(collation='utf8mb4_bin'),
               comment='评估规则文档html(缺陷、需求、立项)',
               existing_nullable=True)
        batch_op.alter_column('type',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=11),
               comment='根分级\r\n0：缺陷-671b\r\n1：需求-617b\r\n2：立项\r\n100:缺陷-小模型\r\n101-需求-小模型',
               existing_nullable=True)

    with op.batch_alter_table('cammand', schema=None) as batch_op:
        batch_op.alter_column('type_child',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=4),
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('ai_sug_score_2', schema=None) as batch_op:
        batch_op.create_table_comment(
        '立项表',
        existing_comment=None
    )
        batch_op.alter_column('update_time',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
        batch_op.alter_column('create_time',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('is_admin_delete',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=4),
               existing_nullable=True)
        batch_op.alter_column('is_delete',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=4),
               existing_nullable=True)
        batch_op.alter_column('state',
               existing_type=mysql.INTEGER(display_width=11),
               comment='0：文件已传到阿里云本地',
               existing_nullable=True)
        batch_op.alter_column('xmind_json',
               existing_type=mysql.TEXT(),
               comment='思维导图json',
               existing_nullable=True)
        batch_op.alter_column('summarize_text',
               existing_type=mysql.TEXT(),
               comment='文档总结-文档摘要',
               existing_nullable=True)
        batch_op.alter_column('all_markdwon_text',
               existing_type=mysql.LONGTEXT(),
               comment='转化后的全文',
               existing_nullable=True)
        batch_op.alter_column('case',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=4),
               comment='阶段：0,1,2,3',
               existing_nullable=True)
        batch_op.alter_column('total_score',
               existing_type=mysql.DECIMAL(precision=4, scale=1),
               comment='总评分',
               existing_nullable=True)
        batch_op.alter_column('select_2',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=255),
               comment='立项-项目发展阶段:\r\n0-首次\r\n1-迭代升级',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('select_1',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=255),
               comment='立项-立项的驱动源：\r\n0：重大项目机会驱动型立项\r\n1：市场机会/威胁分析驱动型立项\r\n2：市场机会/威胁分析+重大项目机会双驱动型立项\r\n3：战略制高点/瓶颈点争夺型立项',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('title',
               existing_type=mysql.VARCHAR(length=255),
               comment='主题',
               existing_nullable=True)
        batch_op.alter_column('file_name',
               existing_type=mysql.VARCHAR(length=255),
               comment='附件名称，文件名',
               existing_nullable=True)
        batch_op.alter_column('file_key',
               existing_type=mysql.VARCHAR(length=255),
               comment='阿里云oss路径',
               existing_nullable=True)
        batch_op.drop_column('summarize_val_sug')

    with op.batch_alter_table('ai_sug_score', schema=None) as batch_op:
        batch_op.create_table_comment(
        '缺陷、产品表',
        existing_comment=None
    )
        batch_op.create_index(batch_op.f('user_id+admin_user_id'), ['user_id', 'admin_user_id'], unique=False)
        batch_op.alter_column('update_time',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
        batch_op.alter_column('create_time',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('model_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_bin', length=64),
               comment='模型名称',
               existing_nullable=True)
        batch_op.alter_column('error_mess',
               existing_type=mysql.TEXT(collation='utf8mb4_bin'),
               comment='失败原因',
               existing_nullable=True)
        batch_op.alter_column('is_admin_delete',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=4),
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('is_delete',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=4),
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('state',
               existing_type=mysql.INTEGER(display_width=11),
               comment='0：暂存\r\n1：已评估\r\n-1：批量评估中\r\n-2：评估中\r\n-3：评估失败，请求超时\r\n-4：返回数据错误',
               existing_nullable=True)

    with op.batch_alter_table('admin_user', schema=None) as batch_op:
        batch_op.alter_column('is_delete',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=4),
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('admin_rights', schema=None) as batch_op:
        batch_op.alter_column('menu',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=4),
               comment='1是menu，0不是',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))

    op.drop_table('modification_log')
    op.drop_table('roles')
    op.drop_table('defect_level')
    op.drop_table('case')
    # ### end Alembic commands ###
