"""modify ai_sug_score_2 add anti_shake_log

Revision ID: a3f82433b460
Revises: 29da68ed93e4
Create Date: 2025-09-04 11:24:43.208934

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a3f82433b460'
down_revision = '29da68ed93e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # 先创建没有外键约束的表
    op.create_table('anti_shake_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('val_id', sa.String(length=50), nullable=True, comment='当日志是缺陷或需求的时候有效'),
    sa.Column('val2_id', sa.Integer(), nullable=True, comment='当日志是立项的时候有效'),
    sa.Column('type', sa.SmallInteger(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine='InnoDB'
    )

    # 然后单独添加外键约束
    # op.create_foreign_key(
    #     'fk_anti_shake_log_val_id',
    #     'anti_shake_log',
    #     'ai_sug_score',
    #     ['val_id'],
    #     ['id'],
    #     ondelete='CASCADE'
    # )

    op.create_foreign_key(
        'fk_anti_shake_log_val2_id',
        'anti_shake_log',
        'ai_sug_score_2',
        ['val2_id'],
        ['id'],
        ondelete='CASCADE'
    )

    op.drop_table('case')
    op.drop_table('doc_ai_aq')

    with op.batch_alter_table('module_to_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('anti_shake_status', sa.String(length=20), nullable=False))
        batch_op.create_foreign_key('fk_module_to_model_model_id', 'models', ['model_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('anti_shake')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('module_to_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('anti_shake', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True, comment='0:不防抖；1：防抖'))
        batch_op.drop_constraint('fk_module_to_model_model_id', type_='foreignkey')
        batch_op.drop_column('anti_shake_status')

    op.create_table('doc_ai_aq',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('file_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('question', mysql.TEXT(collation='utf8mb4_bin'), nullable=True),
    sa.Column('anwser', mysql.TEXT(collation='utf8mb4_bin'), nullable=True),
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_bin',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )

    op.create_table('case',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('text', mysql.TEXT(), nullable=True),
    sa.Column('create_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('update_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )

    # 先删除外键约束
    # op.drop_constraint('fk_anti_shake_log_val_id', 'anti_shake_log', type_='foreignkey')
    op.drop_constraint('fk_anti_shake_log_val2_id', 'anti_shake_log', type_='foreignkey')

    # 然后删除表
    op.drop_table('anti_shake_log')
    # ### end Alembic commands ###