"""table defects delete ForeignKey defect_stages.id

Revision ID: a3fbb9c9e140
Revises: 1fdf236e4cfc
Create Date: 2025-09-01 14:53:59.156932

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a3fbb9c9e140'
down_revision = '1fdf236e4cfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('defects', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('defects_ibfk_4'), type_='foreignkey')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_authenticated')
        batch_op.drop_column('is_anonymous')
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True, comment='用户账户是否激活'))
        batch_op.add_column(sa.Column('is_anonymous', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True, comment='用户是否为匿名用户'))
        batch_op.add_column(sa.Column('is_authenticated', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True, comment='用户是否已认证'))

    with op.batch_alter_table('defects', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('defects_ibfk_4'), 'defect_stages', ['current_stage_id'], ['id'])

    # ### end Alembic commands ###
