"""defect_solution_divisions add status field

Revision ID: a5162619436a
Revises: a3f82433b460
Create Date: 2025-09-07 09:41:15.876879

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a5162619436a'
down_revision = 'a3f82433b460'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('defect_solution_divisions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True, comment='邀请状态'))
    # ### end Alembic commands ###
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('defect_solution_divisions', schema=None) as batch_op:
        batch_op.drop_column('status')
    # ### end Alembic commands ###
