"""add_defect_tables_foreign_key3

Revision ID: adf24d96bda4
Revises: e0f194c2f28f
Create Date: 2025-08-30 16:26:40.648552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adf24d96bda4'
down_revision = 'e0f194c2f28f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('defects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_stage_id', sa.Integer(), nullable=True, comment='当前所处阶段ID'))
        batch_op.create_index('ix_defects_current_stage_id', ['current_stage_id'], unique=False)
        batch_op.create_foreign_key(None, 'defect_stages', ['current_stage_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('defects', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index('ix_defects_current_stage_id')
        batch_op.drop_column('current_stage_id')

    # ### end Alembic commands ###
