"""anti_shake_model_to_moudule

Revision ID: bb699c3552d3
Revises: f3d4aad3cf99
Create Date: 2025-09-03 06:37:03.876842

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bb699c3552d3'
down_revision = 'f3d4aad3cf99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('defect_counters',
    # sa.Column('date', sa.String(length=8), nullable=False),
    # sa.Column('count', sa.Integer(), nullable=True),
    # sa.PrimaryKeyConstraint('date'),
    # mysql_engine='InnoDB'
    # )
    with op.batch_alter_table('defect_flow_history', schema=None) as batch_op:
        batch_op.alter_column('action_type',
               existing_type=mysql.ENUM('CREATE', 'UPDATE', 'APPROVE', 'INVITE_TO_ANALYZE', 'REJECT', 'TRANSFER', 'ASSIGN_DIVISION', 'SUBMIT_SOLUTION', 'REMIND', collation='utf8mb4_bin'),
               type_=sa.String(length=50),
               existing_comment='操作类型',
               existing_nullable=False)

    with op.batch_alter_table('defect_locale_invitations', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('PENDING', 'ACCEPTED', 'REJECTED', 'CANCELLED', collation='utf8mb4_bin'),
               type_=sa.String(length=50),
               existing_comment='邀请状态',
               existing_nullable=True)

    with op.batch_alter_table('defect_rejections', schema=None) as batch_op:
        batch_op.alter_column('rejection_type',
               existing_type=mysql.ENUM('STAGE', 'INVITATION', 'ANALYSIS', 'SOLUTION', collation='utf8mb4_bin'),
               type_=sa.String(length=50),
               existing_comment='驳回类型',
               existing_nullable=False)

    with op.batch_alter_table('defect_reminders', schema=None) as batch_op:
        batch_op.alter_column('reminder_type',
               existing_type=mysql.ENUM('ANALYSIS', 'SOLUTION', collation='utf8mb4_bin'),
               type_=sa.String(length=50),
               existing_comment='跟催类型',
               existing_nullable=False)
        batch_op.alter_column('reminder_status',
               existing_type=mysql.ENUM('SENT', 'VIEWED', 'ACTED', collation='utf8mb4_bin'),
               type_=sa.String(length=50),
               existing_comment='跟催状态',
               existing_nullable=True)

    with op.batch_alter_table('defect_stage_collaborators', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=mysql.ENUM('PRIMARY', 'COLLABORATOR', collation='utf8mb4_bin'),
               type_=sa.String(length=50),
               existing_comment='协作者角色',
               existing_nullable=True)

    with op.batch_alter_table('defect_stage_combine_records', schema=None) as batch_op:
        batch_op.alter_column('evaluation_method',
               existing_type=mysql.ENUM('AUTO', 'MANUAL', collation='utf8mb4_bin'),
               type_=sa.String(length=50),
               existing_comment='评分方式',
               existing_nullable=True)

    with op.batch_alter_table('defect_stage_data', schema=None) as batch_op:
        batch_op.alter_column('data_type',
               existing_type=mysql.ENUM('DEFECT_DESCRIPTION', 'CAUSE_ANALYSIS', 'SOLUTION', 'TEST_RESULT', collation='utf8mb4_bin'),
               type_=sa.String(length=50),
               existing_comment='数据类型，对应问题描述、原因分析、解决措施及验证4个特殊阶段',
               existing_nullable=False)
        batch_op.alter_column('evaluation_method',
               existing_type=mysql.ENUM('AUTO', 'MANUAL', collation='utf8mb4_bin'),
               type_=sa.String(length=50),
               existing_comment='评分方式',
               existing_nullable=True)

    with op.batch_alter_table('defect_stages', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('IN_PROGRESS', 'COMPLETED', 'REJECTED', 'CANCELLED', collation='utf8mb4_bin'),
               type_=sa.String(length=50),
               existing_comment='阶段状态',
               existing_nullable=True)

    with op.batch_alter_table('defects', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('DRAFT', 'OPEN', 'RESOLVED', 'CLOSED', 'REJECTED', collation='utf8mb4_bin'),
               type_=sa.String(length=50),
               existing_comment='缺陷整体状态',
               existing_nullable=True)

    with op.batch_alter_table('email_user_right', schema=None) as batch_op:
        batch_op.alter_column('type_0',
               existing_type=mysql.TINYINT(display_width=4),
               type_=sa.Integer(),
               comment=None,
               existing_comment='0:缺陷管理',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('type_1',
               existing_type=mysql.TINYINT(display_width=4),
               type_=sa.Integer(),
               comment=None,
               existing_comment='1:需求管理',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('type_2',
               existing_type=mysql.TINYINT(display_width=4),
               type_=sa.Integer(),
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('create_time',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('update_time',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))

    with op.batch_alter_table('mobile_user_right', schema=None) as batch_op:
        batch_op.alter_column('user_total_num',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='可邀同事总数',
               existing_nullable=True,
               existing_server_default=sa.text("'10'"))
        batch_op.alter_column('remind_invited_num',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='剩余几次发短信提醒',
               existing_nullable=True,
               existing_server_default=sa.text("'-1'"))
        batch_op.alter_column('request_num',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='可提问总次数',
               existing_nullable=True,
               existing_server_default=sa.text("'10'"))
        batch_op.alter_column('sended_remind_date_message',
               existing_type=mysql.TINYINT(display_width=4),
               type_=sa.Integer(),
               comment=None,
               existing_comment='是否已发到期短信',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('sended_remind_invite_message',
               existing_type=mysql.TINYINT(display_width=4),
               type_=sa.Integer(),
               comment=None,
               existing_comment='用于控制是否发短信',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('sended_remind_request_message',
               existing_type=mysql.TINYINT(display_width=4),
               type_=sa.Integer(),
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('type',
               existing_type=mysql.TINYINT(display_width=4),
               type_=sa.Integer(),
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('state',
               existing_type=mysql.TINYINT(display_width=4),
               type_=sa.Integer(),
               comment=None,
               existing_comment='0为试用状态',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('remind_invited_open',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Integer(),
               comment=None,
               existing_comment='是否开启发短信 0未开，1已开',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('remind_request_open',
               existing_type=mysql.TINYINT(display_width=4),
               type_=sa.Integer(),
               comment=None,
               existing_comment='0未开，1已开',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('remind_date_open',
               existing_type=mysql.TINYINT(display_width=4),
               type_=sa.Integer(),
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('admin_last_update',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('create_time',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('update_time',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
        # batch_op.drop_column('remind_to_date')

    with op.batch_alter_table('module_to_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('anti_shake', sa.SmallInteger(), nullable=True, comment='0:不防抖；1：防抖'))
        batch_op.alter_column('module',
               existing_type=mysql.TINYINT(display_width=64),
               type_=sa.Integer(),
               comment=None,
               existing_comment='0:缺陷 1：需求，2：立项',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('model_id',
               existing_type=mysql.TINYINT(display_width=4),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('create_time',
               existing_type=mysql.DATETIME(),
               nullable=False)
        batch_op.alter_column('update_time',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('sms_queue', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=mysql.TINYINT(display_width=4),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('e1',
               existing_type=mysql.TINYINT(display_width=4),
               type_=sa.Integer(),
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('e2',
               existing_type=mysql.TINYINT(display_width=4),
               type_=sa.Integer(),
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('send_num',
               existing_type=mysql.TINYINT(display_width=4),
               type_=sa.Integer(),
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('create_time',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('update_time',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))

    with op.batch_alter_table('upload_files', schema=None) as batch_op:
        batch_op.alter_column('create_time',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('update_time',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('company_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_bin', length=255),
               comment=None,
               existing_comment='公司名',
               existing_nullable=True,
               existing_server_default=sa.text("''"))
        batch_op.alter_column('employees_num',
               existing_type=mysql.VARCHAR(collation='utf8mb4_bin', length=11),
               comment=None,
               existing_comment='员工数',
               existing_nullable=True)
        batch_op.alter_column('sense',
               existing_type=mysql.VARCHAR(collation='utf8mb4_bin', length=255),
               comment=None,
               existing_comment='场景',
               existing_nullable=True)
        batch_op.alter_column('position',
               existing_type=mysql.VARCHAR(collation='utf8mb4_bin', length=255),
               comment=None,
               existing_comment='职位',
               existing_nullable=True)
        batch_op.alter_column('dept',
               existing_type=mysql.VARCHAR(collation='utf8mb4_bin', length=255),
               comment=None,
               existing_comment='部门',
               existing_nullable=True,
               existing_server_default=sa.text("''"))
        batch_op.alter_column('status',
               existing_type=mysql.TINYINT(display_width=4),
               type_=sa.Integer(),
               comment=None,
               existing_comment='手机用户，0：刚填写手机密码；1：注册完填写完公司\r\n\r\n邮件用户，0未邮箱激活，1已激活',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('is_delete',
               existing_type=mysql.TINYINT(display_width=4),
               type_=sa.Integer(),
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('create_time',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('update_time',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))

    with op.batch_alter_table('val_ai_aq', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=mysql.TINYINT(display_width=4),
               type_=sa.Integer(),
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('create_time',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('update_time',
               existing_type=mysql.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('val_ai_aq', schema=None) as batch_op:
        batch_op.alter_column('update_time',
               existing_type=mysql.DATETIME(),
               nullable=True)
        batch_op.alter_column('create_time',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('type',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=4),
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('update_time',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
        batch_op.alter_column('create_time',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('is_delete',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=4),
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('status',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=4),
               comment='手机用户，0：刚填写手机密码；1：注册完填写完公司\r\n\r\n邮件用户，0未邮箱激活，1已激活',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('dept',
               existing_type=mysql.VARCHAR(collation='utf8mb4_bin', length=255),
               comment='部门',
               existing_nullable=True,
               existing_server_default=sa.text("''"))
        batch_op.alter_column('position',
               existing_type=mysql.VARCHAR(collation='utf8mb4_bin', length=255),
               comment='职位',
               existing_nullable=True)
        batch_op.alter_column('sense',
               existing_type=mysql.VARCHAR(collation='utf8mb4_bin', length=255),
               comment='场景',
               existing_nullable=True)
        batch_op.alter_column('employees_num',
               existing_type=mysql.VARCHAR(collation='utf8mb4_bin', length=11),
               comment='员工数',
               existing_nullable=True)
        batch_op.alter_column('company_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_bin', length=255),
               comment='公司名',
               existing_nullable=True,
               existing_server_default=sa.text("''"))

    with op.batch_alter_table('upload_files', schema=None) as batch_op:
        batch_op.alter_column('update_time',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
        batch_op.alter_column('create_time',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('sms_queue', schema=None) as batch_op:
        batch_op.alter_column('update_time',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
        batch_op.alter_column('create_time',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('send_num',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=4),
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('e2',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=4),
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('e1',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=4),
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('type',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=4),
               existing_nullable=True)

    with op.batch_alter_table('module_to_model', schema=None) as batch_op:
        batch_op.alter_column('update_time',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('create_time',
               existing_type=mysql.DATETIME(),
               nullable=True)
        batch_op.alter_column('model_id',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=4),
               existing_nullable=True)
        batch_op.alter_column('module',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=64),
               comment='0:缺陷 1：需求，2：立项',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.drop_column('anti_shake')

    with op.batch_alter_table('mobile_user_right', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remind_to_date', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='换ui后废弃'))
        batch_op.alter_column('update_time',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
        batch_op.alter_column('create_time',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('admin_last_update',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('remind_date_open',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=4),
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('remind_request_open',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=4),
               comment='0未开，1已开',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('remind_invited_open',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=1),
               comment='是否开启发短信 0未开，1已开',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('state',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=4),
               comment='0为试用状态',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('type',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=4),
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('sended_remind_request_message',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=4),
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('sended_remind_invite_message',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=4),
               comment='用于控制是否发短信',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('sended_remind_date_message',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=4),
               comment='是否已发到期短信',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('request_num',
               existing_type=mysql.INTEGER(display_width=11),
               comment='可提问总次数',
               existing_nullable=True,
               existing_server_default=sa.text("'10'"))
        batch_op.alter_column('remind_invited_num',
               existing_type=mysql.INTEGER(display_width=11),
               comment='剩余几次发短信提醒',
               existing_nullable=True,
               existing_server_default=sa.text("'-1'"))
        batch_op.alter_column('user_total_num',
               existing_type=mysql.INTEGER(display_width=11),
               comment='可邀同事总数',
               existing_nullable=True,
               existing_server_default=sa.text("'10'"))

    with op.batch_alter_table('email_user_right', schema=None) as batch_op:
        batch_op.alter_column('update_time',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
        batch_op.alter_column('create_time',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('type_2',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=4),
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('type_1',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=4),
               comment='1:需求管理',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('type_0',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=4),
               comment='0:缺陷管理',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('defects', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=50),
               type_=mysql.ENUM('DRAFT', 'OPEN', 'RESOLVED', 'CLOSED', 'REJECTED', collation='utf8mb4_bin'),
               existing_comment='缺陷整体状态',
               existing_nullable=True)

    with op.batch_alter_table('defect_stages', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=50),
               type_=mysql.ENUM('IN_PROGRESS', 'COMPLETED', 'REJECTED', 'CANCELLED', collation='utf8mb4_bin'),
               existing_comment='阶段状态',
               existing_nullable=True)

    with op.batch_alter_table('defect_stage_data', schema=None) as batch_op:
        batch_op.alter_column('evaluation_method',
               existing_type=sa.String(length=50),
               type_=mysql.ENUM('AUTO', 'MANUAL', collation='utf8mb4_bin'),
               existing_comment='评分方式',
               existing_nullable=True)
        batch_op.alter_column('data_type',
               existing_type=sa.String(length=50),
               type_=mysql.ENUM('DEFECT_DESCRIPTION', 'CAUSE_ANALYSIS', 'SOLUTION', 'TEST_RESULT', collation='utf8mb4_bin'),
               existing_comment='数据类型，对应问题描述、原因分析、解决措施及验证4个特殊阶段',
               existing_nullable=False)

    with op.batch_alter_table('defect_stage_combine_records', schema=None) as batch_op:
        batch_op.alter_column('evaluation_method',
               existing_type=sa.String(length=50),
               type_=mysql.ENUM('AUTO', 'MANUAL', collation='utf8mb4_bin'),
               existing_comment='评分方式',
               existing_nullable=True)

    with op.batch_alter_table('defect_stage_collaborators', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.String(length=50),
               type_=mysql.ENUM('PRIMARY', 'COLLABORATOR', collation='utf8mb4_bin'),
               existing_comment='协作者角色',
               existing_nullable=True)

    with op.batch_alter_table('defect_reminders', schema=None) as batch_op:
        batch_op.alter_column('reminder_status',
               existing_type=sa.String(length=50),
               type_=mysql.ENUM('SENT', 'VIEWED', 'ACTED', collation='utf8mb4_bin'),
               existing_comment='跟催状态',
               existing_nullable=True)
        batch_op.alter_column('reminder_type',
               existing_type=sa.String(length=50),
               type_=mysql.ENUM('ANALYSIS', 'SOLUTION', collation='utf8mb4_bin'),
               existing_comment='跟催类型',
               existing_nullable=False)

    with op.batch_alter_table('defect_rejections', schema=None) as batch_op:
        batch_op.alter_column('rejection_type',
               existing_type=sa.String(length=50),
               type_=mysql.ENUM('STAGE', 'INVITATION', 'ANALYSIS', 'SOLUTION', collation='utf8mb4_bin'),
               existing_comment='驳回类型',
               existing_nullable=False)

    with op.batch_alter_table('defect_locale_invitations', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=50),
               type_=mysql.ENUM('PENDING', 'ACCEPTED', 'REJECTED', 'CANCELLED', collation='utf8mb4_bin'),
               existing_comment='邀请状态',
               existing_nullable=True)

    with op.batch_alter_table('defect_flow_history', schema=None) as batch_op:
        batch_op.alter_column('action_type',
               existing_type=sa.String(length=50),
               type_=mysql.ENUM('CREATE', 'UPDATE', 'APPROVE', 'INVITE_TO_ANALYZE', 'REJECT', 'TRANSFER', 'ASSIGN_DIVISION', 'SUBMIT_SOLUTION', 'REMIND', collation='utf8mb4_bin'),
               existing_comment='操作类型',
               existing_nullable=False)

    # op.drop_table('defect_counters')
    # ### end Alembic commands ###
