"""table defects add  ForeignKey defect_stages.id

Revision ID: c48e20265398
Revises: a3fbb9c9e140
Create Date: 2025-09-01 15:08:39.983849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c48e20265398'
down_revision = 'a3fbb9c9e140'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('defects', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'defect_stages', ['current_stage_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('defects', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
