"""add_defect_tables_foreign_key2

Revision ID: e0f194c2f28f
Revises: 3a5ac92d784e
Create Date: 2025-08-30 14:38:00.015444

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e0f194c2f28f'
down_revision = '3a5ac92d784e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('defects', schema=None) as batch_op:
        # batch_op.drop_index(batch_op.f('ix_defects_current_stage_id'))
        # batch_op.drop_constraint(batch_op.f('defects_ibfk_2'), type_='foreignkey')
        batch_op.drop_column('current_stage_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('defects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_stage_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='当前所处阶段ID'))
        batch_op.create_foreign_key(batch_op.f('defects_ibfk_2'), 'defect_stages', ['current_stage_id'], ['id'])
        batch_op.create_index(batch_op.f('ix_defects_current_stage_id'), ['current_stage_id'], unique=False)

    # ### end Alembic commands ###
