"""delete name unique

Revision ID: ebefed04b798
Revises: 17d3b98f292f
Create Date: 2025-10-15 09:53:05.953072

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ebefed04b798'
down_revision = '17d3b98f292f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('name'))

    with op.batch_alter_table('tech_groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('name'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tech_groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('name'), ['name'], unique=True)

    with op.batch_alter_table('product_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('name'), ['name'], unique=True)
    # ### end Alembic commands ###
