"""add table defect_counters for defect_number

Revision ID: f3d4aad3cf99
Revises: 6114121f5c4c
Create Date: 2025-09-01 18:07:56.431335

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f3d4aad3cf99'
down_revision = '6114121f5c4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('defect_counters',
    sa.Column('date', sa.String(length=8), nullable=False),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('date'),
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('defect_flow_history', schema=None) as batch_op:
        batch_op.alter_column('action_type',
               existing_type=sa.String(length=50),
               type_=mysql.ENUM('CREATE', 'UPDATE', 'APPROVE', 'INVITE_TO_ANALYZE', 'REJECT', 'TRANSFER', 'ASSIGN_DIVISION', 'SUBMIT_SOLUTION', 'REMIND'),
               existing_comment='操作类型',
               existing_nullable=False)

    op.drop_table('defect_counters')
    # ### end Alembic commands ###
