"""添加缺陷处理流程的模型

Revision ID: f7fa181e0663
Revises: c9e8cfa3a41e
Create Date: 2025-08-29 18:40:56.058658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7fa181e0663'
down_revision = 'c9e8cfa3a41e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('create_time', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_column('create_time')
        batch_op.drop_column('create_user_id')

    # ### end Alembic commands ###
