"""Add three new models

Revision ID: fc5b87daa39b
Revises: 608e23631437
Create Date: 2025-08-27 15:09:16.035959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc5b87daa39b'
down_revision = '608e23631437'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('defect_level',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('critical_defects', sa.Float(), nullable=True),
    sa.Column('major_defects', sa.Float(), nullable=True),
    sa.Column('minor_defects', sa.Float(), nullable=True),
    sa.Column('suggestion_defects', sa.Float(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('modification_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('defect_level_id', sa.Integer(), nullable=False),
    sa.Column('modifier', sa.String(length=50), nullable=False),
    sa.Column('field_name', sa.String(length=50), nullable=False),
    sa.Column('old_value', sa.Float(), nullable=False),
    sa.Column('new_value', sa.Float(), nullable=False),
    sa.Column('modified_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['defect_level_id'], ['defect_level.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('modification_log')
    op.drop_table('defect_level')
    # ### end Alembic commands ###
